USE [master]
GO

/****** Object:  Database [InventoryСontrol]    Script Date: 24.12.2022 1:31:35 ******/
CREATE DATABASE [InventoryСontrol]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventoryСontrol', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\InventoryСontrol.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InventoryСontrol_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\InventoryСontrol_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryСontrol].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoryСontrol] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoryСontrol] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoryСontrol] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoryСontrol] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoryСontrol] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoryСontrol] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoryСontrol] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoryСontrol] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryСontrol] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoryСontrol] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoryСontrol] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoryСontrol] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoryСontrol] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoryСontrol] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoryСontrol] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoryСontrol] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoryСontrol] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoryСontrol] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoryСontrol] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoryСontrol] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoryСontrol] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoryСontrol] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoryСontrol] SET RECOVERY FULL 
GO

ALTER DATABASE [InventoryСontrol] SET  MULTI_USER 
GO

ALTER DATABASE [InventoryСontrol] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoryСontrol] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventoryСontrol] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventoryСontrol] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InventoryСontrol] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventoryСontrol] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [InventoryСontrol] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InventoryСontrol] SET  READ_WRITE 
GO

