//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActPriemka
    {
        public int id_priemka { get; set; }
        public string NumberPriemka { get; set; }
        public Nullable<int> placepriemka_id { get; set; }
        public Nullable<System.DateTime> PriemkaCreatedDate { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> Insurance_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> shipper_id { get; set; }
    
        public virtual Insurance_id Insurance_id1 { get; set; }
        public virtual PlacePriemka PlacePriemka { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
