//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsNakladnay
    {
        public int id_itemNakladnay { get; set; }
        public Nullable<int> equip_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> id_nakladnay { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Universalniy_Dogovor_peredachi Universalniy_Dogovor_peredachi { get; set; }
    }
}
