//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public int id_log { get; set; }
        public string UserLogin { get; set; }
        public string Operation { get; set; }
        public string ChangeData { get; set; }
        public string NameData { get; set; }
        public Nullable<System.DateTime> TimeChange { get; set; }
    }
}
