//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.BdWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_orders { get; set; }
        public Nullable<int> Equipment_id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> priceForOne { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateOver { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Status Status { get; set; }
    }
}
